Bank/Bank/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path,include

from Bank import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bank/bankapp/urls.py
from . import views
from django.urls import path

app_name = 'bankapp'    #namespace

urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('user/',views.user,name='user'),
    path('form/',views.form,name="form"),
]

Bank/bankapp/models.py
from django.db import models

# Create your models here.
class RegForm(models.Model):
    name = models.TextField()
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.TextField()
    phone = models.IntegerField()
    email = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    district = models.TextField()
    branch = models.TextField()
    account_type = models.TextField()
    mater_provi = models.TextField()

Bank/bankapp/forms.py
from django import forms
from django.db import models

class RegistrationForm(forms.Form):
    name = forms.CharField()
    dob = forms.DateField()
    age = forms.IntegerField()
    gender = forms.ChoiceField(choices=[(‘male’,‘Male’), (‘female’, ‘Female’), (‘transgender’, ‘Transgender’)])
    phone_number = forms.CharField()
    email = forms.EmailField()
    address = forms.CharField(widget=forms.Textarea)
    district = forms.ChoiceField(choices=[(‘thrissur’, ‘Thrissur’), (‘ernamkulam’, ‘Ernamkulam’), (‘palakkad’, ‘Palakkad’), (‘kottayam’, ‘Kottayam’), (‘trivandrum’, ‘Trivandrum’)])
    branch = forms.ChoiceField(choices=)
    account_type = forms.ChoiceField(choices=[(‘savings’, ‘Savings’), (‘current’, ‘Current’)])
    materials_required = forms.MultipleChoiceField(choices=[(‘debit’, ‘Debit Card’), (‘credit’, ‘Credit Card’), (‘cheque’, ‘Chequebook’)], widget=forms.CheckboxSelectMultiple)

Bank/bankapp/views.py
from django.shortcuts import render,redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User

# Create your views here.
from bankapp.models import RegForm


def home(request):
    return render(request,'home.html')


def login(request):
        if request.user.is_authenticated:
            return render(request,'user.html')
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return render(request,'user.html')
            else:
                messages.info(request, "Invalid credentials")
                return render(request, 'login.html')

        return render(request, 'login.html')


def logout(request):
        auth.logout(request)
        return redirect('/')

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['cpassword']
        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username taken")
                return render(request, 'register.html')
            else:
                user = User.objects.create_user(username=username,password=password)

                user.save()

                return render(request, 'register.html')
        else:
            messages.info(request, "password is not matched")
            return redirect('register')
        return redirect('/')
    return render(request, 'register.html')

def user(request):
    return render(request,'user.html')
def form(request):
    if request.method == 'POST':
        name = request.POST['name']
        dob = request.POST['dob']
        age =  request.POST['age']
        gender = request.POST['gender']
        phoneNumber =  request.POST['phoneNumber']
        email = request.POST['email']
        address =  request.POST['address']
        district =  request.POST['district']
        branch =  request.POST['branch']
        account = request.POST['account']
        materials = request.POST['materials']

        reg = RegForm.objects.create(name=name,dob=dob,age=age,gender=gender,phone=phoneNumber,email=email,address=address,
                               district=district,branch=branch,account_type=account,mater_provi=materials)
        reg.save()
        auth.logout(request)
        return render(request,'submittion.html')
    return render(request,'form.html')

Bank/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
     <script src="{% static 'js/fontv6.js' %}" ></script>
    <!-- <script src="https://kit.fontawesome.com/bdbe02bb0d.js" crossorigin="anonymous"></script> -->
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
  {% include 'navbar.html' %}

  {% block content %}
  {% endblock %}

    <!-- {% include 'footer.html' %} -->

</div>
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
<script>
    function openForm(){
        document.getElementById('form1').style.display = "block";
    }
</script>
</body>
</html>

</body>
</html>

Bank/templates/footer.html
<footer class="py-3 my-4" style="position:sticky;position: -webkit-sticky;bottom:0;left:0;">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">&copy; 2023 Company, Inc</p>
  </footer>

Bank/templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="form1">
    <form method="post" action="{% url 'bankapp:form' %}">
        {% csrf_token %}
        <table>
  <tr>
    <td><label for="name">Name:</label></td>
    <td><input type="text" name="name" id="name" placeholder="your name"></td>
  </tr>
  <tr>
    <td><label for="dob">DOB:</label></td>
    <td><input type="date" name="dob" id="dob" placeholder="DOB"></td>
  </tr>
  <tr>
    <td><label >Age:</label></td>
    <td><input type="number" name="age" id="number" placeholder="Age"></td>
  </tr>
  <tr>
    <td><label >Gender:</label></td>
    <td>Male: <input type="radio" name="gender" value="male">
      Female: <input type="radio" name="gender" value="female">
      Transgender: <input type="radio" name="gender" value="Transgender"></td>
  </tr>
  <tr>
    <td><label for="phoneNumber">Phone Number:</label></td>
    <td><input type="number" name="phoneNumber" id="phoneNumber"></td>
  </tr>
  <tr>
    <td><label for="email">Email:</label></td>
    <td><input type="text" name="email" id="email" placeholder="your email"></td>
  </tr>
  <tr>
    <td><label for="address">Address:</label></td>
    <td><textarea name="address" id="address" placeholder="Address"></textarea></td>
  </tr>


  <tr>
    <td><label for="district">District</label></td>
    <td>
      <select name="district" id="district" class="district-dropdown">
        <option value="">--Select District--</option>
        <option value="Thrissur">Thrissur</option>
        <option value="Ernamkulam">Ernamkulam</option>
        <option value="Palakkad">Palakkad</option>
        <option value="Kottayam">Kottayam</option>
        <option value="Trivandrum">Trivandrum</option>
      </select>
    </td>
  </tr>
  <tr>
    <td> <label for="branch">Branch:</label></td>
    <td>
      <select id="branch" name="branch" class="branch-dropdown">
        <option value="">--Select Branch--</option>
      </select></td>
  </tr>
  <tr>
    <td><label for="Account">Account Type</label></td>
    <td>
      <select id="account" name="account">
        <option value="">Choose</option>
        <option value="Savings">Savings</option>
        <option value="Current">Current</option>
      </select></td>
  </tr>
  <tr>
    <td><label>Materials Provided :</label></td>
    <td>
      <input type="checkbox" id="debit" name="materials" value="Debit Card">
      <label for="debit">Debit Card</label>
      <input type="checkbox" id="credit" name="materials" value="Credit Card">
      <label for="credit">Credit Card</label>
      <input type="checkbox" id="cheque" name="materials" value="Chequebook">
      <label for="debit">Cheque Book</label></td>
  </tr>
  <tr div class="button">
    <td colspan="2"><input type="submit" class="submit" value="Register" onclick="return formValidation()" /></td>
  </tr>
</table>
</form>
</div>
{% endblock %}

Bank/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<img src="{% static 'images/bank3.jpg' %}" class="d-block w-100" alt="bank" height="550px">
{% endblock %}

Bank/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form method="post" action="{% url 'bankapp:login' %}">
        {% csrf_token %}
        <div class="mb-3">
        <label for="exampleInputUsername" class="form-label">UserName</label>
    <input type="text" class="form-control" id="exampleInputUsername" name="username" aria-describedby="emailHelp">
        </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" name="password" id="exampleInputPassword1">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<div class="mb-3">
    <a href="{% url 'bankapp:register' %}">Register</a>
</div>


{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
{% endblock %}

Bank/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bankapp:home' %}">Home</a>
        </li>
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="" role="button"  id="navbarDropdwon" data-bs-toggle="dropdown"
             aria-expanded="false">Branches
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Wayanad">wayanad</a></li>
          </ul>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> Hello {{user.username}}</li>
        <li calss="nav-item"><a class="nav-link" href="{% url 'bankapp:logout' %}">Logout</a></li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bankapp:login' %}">Login/Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<br><br>

Bank/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form action="{% url 'bankapp:register' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Username</label>
    <input type="text" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" name="password"  id="exampleInputPassword1">
  </div>
        <div class="mb-3">
    <label for="exampleInputCPassword" class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cpassword" id="exampleInputCPassword">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}

{% endblock %}

Bank/templates/submittion.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Application Accepted</h1>
</style>

{% endblock %}

Bank/templates/user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<a href="{% url 'bankapp:form' %}">Form</a>
<style>
    a{
        text-decoration:None;
        border:1px solid black;
        padding:3px;
    }
</style>

{% endblock %}